"""Контрольная миграция 3

Revision ID: 878341fcd07b
Revises: a8be385892a8
Create Date: 2024-12-25 14:30:11.084240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '878341fcd07b'
down_revision = 'a8be385892a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avatar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avatar', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
