"""Контрольная миграция 2

Revision ID: a8be385892a8
Revises: 3a147c0e44ac
Create Date: 2024-12-25 14:12:56.170983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8be385892a8'
down_revision = '3a147c0e44ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('temp', sa.Float(), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('hardMode', sa.Boolean(), nullable=False),
    sa.Column('assist_id', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avatar')
    # ### end Alembic commands ###
